In [2]:
import pandas as pd
import numpy as np

In [3]:
# [1] 파일을 읽어와 맨 처음 3개 행을 가져오기
df = pd.read_excel('data_2.xlsx')
A = df.head(3)
A

A  B  C  D
0  A  3  1  X
1  A  1  2  X
2  A  0  5  Y

In [4]:
# [2] head, tail -> Series, DataFrame의 맨 처음부터 n개, 맨 마지막 n개 가져오기
df.head(2)

A  B  C  D
0  A  3  1  X
1  A  1  2  X

In [5]:
df.tail(2)

A  B  C  D
7  C  1  1  Y
8  C  3  2  X

### 1.Series, DataFrame의 속성(attribute)

In [6]:
s = df['A']
# 차원
display(df.ndim, s.ndim)

2

1

In [7]:
# 각 차원의 크기
display(df.shape, s.shape)

(9, 4)

(9,)

In [8]:
# 값
display(df.values, s.values)

array([['A', 3, 1, 'X'],
       ['A', 1, 2, 'X'],
       ['A', 0, 5, 'Y'],
       ['B', 1, 6, 'X'],
       ['B', 7, 2, 'Y'],
       ['B', 3, 3, 'X'],
       ['C', 2, 4, 'X'],
       ['C', 1, 1, 'Y'],
       ['C', 3, 2, 'X']], dtype=object)

array(['A', 'A', 'A', 'B', 'B', 'B', 'C', 'C', 'C'], dtype=object)

In [9]:
# index, columns
# = (assignment)에 의해 수정될 수 있음
display(df.index, df.columns, s.index)

RangeIndex(start=0, stop=9, step=1)

Index(['A', 'B', 'C', 'D'], dtype='object')

RangeIndex(start=0, stop=9, step=1)

In [10]:
# 전치행렬
df.T

0  1  2  3  4  5  6  7  8
A  A  A  A  B  B  B  C  C  C
B  3  1  0  1  7  3  2  1  3
C  1  2  5  6  2  3  4  1  2
D  X  X  Y  X  Y  X  X  Y  X

In [11]:
# dtype 확인
display(df.dtypes, s.dtype)

A    object
B     int64
C     int64
D    object
dtype: object

dtype('O')

### 2.Pandas Operation
- index, columns에 대한 element-wise 방식
- Series, DataFrame + Scalar - Broadcasting 후 element-wise

In [12]:
x1 = pd.Series([1,2,3,4], index=[0, 1, 2, 3])
y1 = pd.Series([5,6,7,8], index=[3, 2, 1, 0])
#display(x1, y1)
x1 + y1

0    9
1    9
2    9
3    9
dtype: int64

In [13]:
x1 = pd.Series([1,2,3,4], index=[0, 1, 2, 3])    # 0이 NaN
y1 = pd.Series([5,6,7,8], index=[3, 2, 1, 4])    # 4가 NaN
#display(x1, y1)
x1 + y1

0    NaN
1    9.0
2    9.0
3    9.0
4    NaN
dtype: float64

In [14]:
x1 = pd.DataFrame([[1,2],[3,4]])
y1 = pd.DataFrame([[5,6],[7,8]])
#display(x1, y1)
display(x1 + y1, x1 + 3)

0   1
0   6   8
1  10  12

0  1
0  4  5
1  6  7

In [15]:
x1 = pd.DataFrame([[1,2],[3,4]], index=['A', 'B'])
y1 = pd.DataFrame([[5,6],[7,8]])
display(x1, y1)
display(x1 + y1)

0  1
A  1  2
B  3  4

0  1
0  5  6
1  7  8

0   1
A NaN NaN
B NaN NaN
0 NaN NaN
1 NaN NaN

### 3.Pandas Selection - Indexing & Slicing

#### 3-1.Series

In [16]:
# [1] index의 dtype이 integer인 경우
s1 = pd.Series([1,2,3,4,5], index=[1,2,3,4,5])
s1

1    1
2    2
3    3
4    4
5    5
dtype: int64

In [17]:
# single element indexer  - 차원 감소 (Scalar)
# label 사용 (integer index 아님!)
s1[4],  s1.loc[4]

(4, 4)

In [18]:
# .iloc[]  => integer index 사용
s1.iloc[0], s1.iloc[-1]

(1, 5)

In [19]:
# index array indexer  - 차원 유지 (Series)
# label 사용 (integer index 아님!)
s1[[1, 2, 4]], s1.loc[[1, 2, 4]]

(1    1
 2    2
 4    4
 dtype: int64,
 1    1
 2    2
 4    4
 dtype: int64)

In [20]:
 s1.iloc[[0, 2, 4]]

1    1
3    3
5    5
dtype: int64

In [21]:
# boolean array indexer
s1[s1%2==0], s1.loc[s1%2==0]

(2    2
 4    4
 dtype: int64,
 2    2
 4    4
 dtype: int64)

In [22]:
# 안어울림! - 비추 - 사용하지 마세용
s1.iloc[(s1%2==0).to_numpy()]

2    2
4    4
dtype: int64

In [23]:
pd.__version__

'1.5.0'

In [24]:
# slice indexer
# integer index 사용
s1[2:-1], s1.iloc[2:-1]

C:\Users\Admin\AppData\Local\Temp\ipykernel_14584\493641307.py:3: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  s1[2:-1], s1.iloc[2:-1]


(3    3
 4    4
 dtype: int64,
 3    3
 4    4
 dtype: int64)

In [25]:
# .loc[start:stop]  # stop을 포함한다
s1.loc[1:3]

1    1
2    2
3    3
dtype: int64

In [26]:
# [2] index의 dtype이 integer가 아닌 경우
s2 = pd.Series([1,2,3,4,5], index=list('ABCDE'))
s2

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [27]:
# single element indexer  - 차원 감소 (Scalar)
s2[4], s2['E']

(5, 5)

In [28]:
# index array indexer  - 차원 유지 (Series)
s2[[0, 2, 4]], s2[['A', 'C', 'E']]

(A    1
 C    3
 E    5
 dtype: int64,
 A    1
 C    3
 E    5
 dtype: int64)

In [34]:
# boolean array indexer - 비추, 사용하지 않음
s2[(s1%2==0).to_list()]

B    2
D    4
dtype: int64

In [30]:
# slice indexer - 주의
# integer - stop(포함하지 않음)
# integer아닌 경우 - stop(포함함)
s2[2:4], s2['C':'D']

(C    3
 D    4
 dtype: int64,
 C    3
 D    4
 dtype: int64)

#### 3-2.DataFrame

In [31]:
df = pd.DataFrame(np.arange(1, 10).reshape(3, 3),
                 index=list("ABC"), columns=['X1', 'X2', 'X3'])
df

X1  X2  X3
A   1   2   3
B   4   5   6
C   7   8   9

In [32]:
# basic indexing  - 1개의 indexer만 사용
df[]

SyntaxError: invalid syntax (3867210914.py, line 2)

In [ ]:
# basic indexing - single element indexer (column label) - Series 1개
df['X1']

A    1
B    4
C    7
Name: X1, dtype: int32

In [ ]:
# basic indexing - index array indexer (column label) - DataFrame 
df[['X1', 'X3']]

X1  X3
A   1   3
B   4   6
C   7   9

In [ ]:
df.shape

(3, 3)

In [ ]:
# basic indexing - boolean array indexer (row - index 개수)
# dtype = bool, size = df.shape[0]
df[[True, True, False]]

X1  X2  X3
A   1   2   3
B   4   5   6

In [ ]:
df[df['X1'] % 2 ==1]

X1  X2  X3
A   1   2   3
C   7   8   9

In [ ]:
# basic indexing - slice indexer (row - index label)
df['B':'C']

X1  X2  X3
B   4   5   6
C   7   8   9

In [ ]:
# Selection by label - 2개의 indexer 사용 가능
df.loc[]

In [ ]:
# Selection by label - single element
df.loc['A', 'X2']

2

In [ ]:
# Selection by label - single element
df.loc['A', :]

X1    1
X2    2
X3    3
Name: A, dtype: int32

In [ ]:
# Selection by label - single element
df.loc[:, 'X2']

A    2
B    5
C    8
Name: X2, dtype: int32

In [ ]:
# Selection by label - index array
df.loc[['A', 'C'], ['X1', 'X2']]

X1  X2
A   1   2
C   7   8

In [ ]:
# Selection by label - index array
df.loc[['A', 'C'],:]

X1  X2  X3
A   1   2   3
C   7   8   9

In [ ]:
# Selection by label - index array
df.loc['A',['X1', 'X2']]

X1    1
X2    2
Name: A, dtype: int32

In [ ]:
# Selection by label  - boolean array indexer 
df.loc[[True, True, False], [True, False, True]]

X1  X3
A   1   3
B   4   6

In [ ]:
df.loc[df['X1']%2==0, ['X1', 'X3']]

X1  X3
B   4   6

In [ ]:
# Selection by label  - slice indexer 
# start:stop:step  # stop을 포함한다
df.loc[['A','B'], 'X2':'X3']

X2  X3
A   2   3
B   5   6

In [ ]:
# Selection by integer - 2개의 indexer 사용 가능
df.iloc[]

In [ ]:
# Selection by integer - single element indexer
df.iloc[0, 2]

3

In [ ]:
# Selection by integer - single element indexer (자주 사용)
df.iloc[:, -1]

A    3
B    6
C    9
Name: X3, dtype: int32

In [ ]:
# Selection by integer - index array indexer
df.iloc[[0, 2], [1, -1]]

X2  X3
A   2   3
C   8   9

In [ ]:
# Selection by integer - boolean array indexer  - 비비비비추
df.iloc[(df['X1']%2==0).to_numpy(), [0, 2]]

X1  X3
B   4   6

In [ ]:
# Selection by integer - slice indexer (자주 사용)
df.iloc[:2, ]

X1  X2  X3
A   1   2   3
B   4   5   6

In [ ]:
# Selection by integer - slice indexer (자주 사용)
df.iloc[:, :-1]

X1  X2
A   1   2
B   4   5
C   7   8

In [ ]:
# 특정 조건 만족하는 열 추출
df[df%2==0]

X1   X2   X3
A  NaN  2.0  NaN
B  4.0  NaN  6.0
C  NaN  8.0  NaN

###  indexing 연습? ( 교재 내용 아님, 강사 마음대로)

In [ ]:
# https://github.com/mwaskom/seaborn-data
import seaborn as sns
df = sns.load_dataset('titanic')
df.head(3)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True

In [ ]:
# https://github.com/mwaskom/seaborn-data
import seaborn as sns
df = sns.load_dataset('tips')
df.head(3)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [ ]:
df.shape

(244, 7)

In [ ]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

#### 필수 
- df.info()
- df.describe() : count, mean, std, min, Q1, Q2, Q3, max 
- df.sum()
- df.max()
- df.min()
- df.std()
- df.var()
- df.quantile()
- df.sort_index()
- df.sort_values(...)
- s.str.replace(...)
- s.unique()
- s.value_count()
- df.round(), s.round()
- df.dropna(...)
- df.fillna(...)

In [ ]:
# [1] DataFrame에 대한 정보 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [ ]:
# [2] Series에 대한 정보 확인
df['total_bill'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 244 entries, 0 to 243
Series name: total_bill
Non-Null Count  Dtype  
--------------  -----  
244 non-null    float64
dtypes: float64(1)
memory usage: 2.0 KB


In [ ]:
# [3] DataFrame에 대한 통계값 확인 - 숫자 column에 대해 
df.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
# [4] Series에 대한 통계값 확인 - 숫자 column에 대해 
df['size'].describe()

count    244.000000
mean       2.569672
std        0.951100
min        1.000000
25%        2.000000
50%        2.000000
75%        3.000000
max        6.000000
Name: size, dtype: float64

In [ ]:
# [5] DataFrame에 대한 통계값 확인 - 범주형 column에 대해 


In [ ]:
# [6] 특정 통계량 구하기 - mean, var, std, min, max, quantile, median
df.sum(axis=0, numeric_only=True)

total_bill    4827.77
tip            731.58
size           627.00
dtype: float64

### DataFrame.sum()
- DataFrame.sum(axis=0, skipna=True, level=None, numeric_only=None, min_count=0, **kwargs)

In [ ]:
arr = np.arange(1, 10).reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
df2 = pd.DataFrame(arr, index=list('ABC'), columns=list('XYZ'))
df2

X  Y  Z
A  1  2  3
B  4  5  6
C  7  8  9

In [ ]:
arr.sum(axis=None), df2.sum(axis=0, numeric_only=True).sum()

(45, 45)

In [ ]:
arr.sum(axis=0), df2.sum(axis=0)#.to_numpy()

(array([12, 15, 18]),
 X    12
 Y    15
 Z    18
 dtype: int64)

In [ ]:
arr.sum(axis=1), df2.sum(axis=1)#.to_numpy()

(array([ 6, 15, 24]),
 A     6
 B    15
 C    24
 dtype: int64)

In [ ]:
df3 = pd.DataFrame(arr.copy(), index=list('ABC'), columns=list('XYZ'))
df3.iloc[0,0] = np.nan
df3

X  Y  Z
A  NaN  2  3
B  4.0  5  6
C  7.0  8  9

In [ ]:
df3.sum(axis=0, skipna=True)

X    11.0
Y    15.0
Z    18.0
dtype: float64

In [ ]:
df3.sum(axis=0, skipna=False)

X     NaN
Y    15.0
Z    18.0
dtype: float64

In [ ]:
arr2 = arr.astype('float32').copy()
arr2[0,0] = np.nan   # float NaN
display(arr2)
arr2.sum(axis=0)

array([[nan,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

array([nan, 15., 18.], dtype=float32)

In [ ]:
df2.std(axis=0)

X    3.0
Y    3.0
Z    3.0
dtype: float64

In [ ]:
df2.var(axis=0)

X    9.0
Y    9.0
Z    9.0
dtype: float64

In [ ]:
df2.median(axis=0)

X    4.0
Y    5.0
Z    6.0
dtype: float64

In [ ]:
df2.min(axis=0).max()

3

In [ ]:
df2.max(axis=0).min()

7

In [ ]:
df.quantile([0.25, 0.5, 0.75])

total_bill     tip  size
0.25     13.3475  2.0000   2.0
0.50     17.7950  2.9000   2.0
0.75     24.1275  3.5625   3.0

In [ ]:
df['tip'].quantile([0.25, 0.5, 0.75])

0.25    2.0000
0.50    2.9000
0.75    3.5625
Name: tip, dtype: float64

### DataFrame.sort_values()
- DataFrame.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last', ignore_index=False, key=None)
- by : 정렬기준이 되는 column, 1개 column, 여러 개 column(목록, n차정렬)
- ascending : True - 오름차순, False - 내림차순

In [ ]:
# tip의 내림차순 정렬
df.sort_values(by='tip', ascending=False)

total_bill    tip     sex smoker   day    time  size
170       50.81  10.00    Male    Yes   Sat  Dinner     3
212       48.33   9.00    Male     No   Sat  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
..          ...    ...     ...    ...   ...     ...   ...
0         16.99   1.01  Female     No   Sun  Dinner     2
236       12.60   1.00    Male    Yes   Sat  Dinner     2
111        7.25   1.00  Female     No   Sat  Dinner     1
67         3.07   1.00  Female    Yes   Sat  Dinner     1
92         5.75   1.00  Female    Yes   Fri  Dinner     2

[244 rows x 7 columns]

In [ ]:
# size의 오름차순, tip의 내림차순 정렬
df.sort_values(by=['size','tip'], ascending=[True, False])

total_bill   tip     sex smoker   day    time  size
222        8.58  1.92    Male    Yes   Fri   Lunch     1
82        10.07  1.83  Female     No  Thur   Lunch     1
67         3.07  1.00  Female    Yes   Sat  Dinner     1
111        7.25  1.00  Female     No   Sat  Dinner     1
88        24.71  5.85    Male     No  Thur   Lunch     2
..          ...   ...     ...    ...   ...     ...   ...
187       30.46  2.00    Male    Yes   Sun  Dinner     5
141       34.30  6.70    Male     No  Thur   Lunch     6
143       27.05  5.00  Female     No  Thur   Lunch     6
156       48.17  5.00    Male     No   Sun  Dinner     6
125       29.80  4.20  Female     No  Thur   Lunch     6

[244 rows x 7 columns]

### Series에서 사용하는 것 들
- s.unique()
- s.value_counts()
- s.str.replace()  # s.dype => object(str)

In [ ]:
df3 = df.copy()
df3.loc[:, 'sex':'time'] = df3.loc[:, 'sex':'time'].astype('str')
df3.dtypes

total_bill    float64
tip           float64
sex            object
smoker         object
day            object
time           object
size            int64
dtype: object

In [ ]:
df3['time'].unique()

array(['Dinner', 'Lunch'], dtype=object)

In [ ]:
df3['size'].unique()

array([2, 3, 4, 1, 6, 5], dtype=int64)

In [ ]:
# 범주별 sample 개수
df3['time'].value_counts()

Dinner    176
Lunch      68
Name: time, dtype: int64

In [ ]:
# 범주별 sample 비율
df3['time'].value_counts(normalize=True)

Dinner    0.721311
Lunch     0.278689
Name: time, dtype: float64

In [ ]:
df3['day'].value_counts().sort_index(ascending=False)

Thur    62
Sun     76
Sat     87
Fri     19
Name: day, dtype: int64

In [ ]:
df3.sort_index(axis=1).head(2)

day     sex  size smoker    time   tip  total_bill
0  Sun  Female     2     No  Dinner  1.01       16.99
1  Sun    Male     3     No  Dinner  1.66       10.34

In [ ]:
df3['smoker'].str.replace('No', 'N').str.replace('Yes', 'Y')

0      N
1      N
2      N
3      N
4      N
      ..
239    N
240    Y
241    Y
242    N
243    N
Name: smoker, Length: 244, dtype: object

In [ ]:
df3['smoker'].replace(['No','Yes'], ['N','Y'])

0      N
1      N
2      N
3      N
4      N
      ..
239    N
240    Y
241    Y
242    N
243    N
Name: smoker, Length: 244, dtype: object

In [ ]:
df3['smoker'].replace({'No':'N','Yes':'Y'})

0      N
1      N
2      N
3      N
4      N
      ..
239    N
240    Y
241    Y
242    N
243    N
Name: smoker, Length: 244, dtype: object

In [ ]:
df3['size'].replace(2, 0)

0      0
1      3
2      3
3      0
4      4
      ..
239    3
240    0
241    0
242    0
243    0
Name: size, Length: 244, dtype: int64

In [ ]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
# column의 일부를 변경하고자 할 때
df = df.rename(columns={'tip':'TIP', 'day':'weekday'})
df.head()

total_bill   TIP     sex smoker weekday    time  size
0       16.99  1.01  Female     No     Sun  Dinner     2
1       10.34  1.66    Male     No     Sun  Dinner     3
2       21.01  3.50    Male     No     Sun  Dinner     3
3       23.68  3.31    Male     No     Sun  Dinner     2
4       24.59  3.61  Female     No     Sun  Dinner     4

In [ ]:
df['total_bill'].round(1).head(5)

0    17.0
1    10.3
2    21.0
3    23.7
4    24.6
Name: total_bill, dtype: float64