In [1]:
test = '13579'
test[::-1]


'97531'

In [8]:
a = [1, 3, 5, 7]
a.insert(len(a), 10)
a


[1, 3, 5, 7, 10]

In [1]:
grade = {'S': 10.0, 'A+': 9.5, 'A': 9.0,
         'B+': 8.5, 'B': 8.0, 'C': 7.5, 'D': 6.5}

grade['A']


9.0

In [1]:
A = 1
print(A)
sum()


1


TypeError: sum() takes at least 1 positional argument (0 given)

In [1]:
tot =0
for i in range(1,10,2):
    if i%3==0:
        break
    tot=tot+i
print(tot)

1


In [15]:
'B' and 0

0

In [6]:
'A' or 'B'

'A'

In [ ]:
int(h))

In [11]:
import numpy as np
from numpy import arange

b=arange(1,7).reshape(2,-1)
b[:1]

array([[1, 2, 3]])

In [14]:
x = np.array([0,1,2,3,4,5,6,7,8])

In [13]:
fidx = [3, 7, 1]
x[fidx]

array([3, 7, 1])

In [15]:
fidx =[[3, 7],
       [4, 2]]
fidx = np.array(fidx)
x[fidx]

array([[3, 7],
       [4, 2]])

In [16]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)

In [23]:
array=array2d[0,1]
print(array)
array3 = array2d[[0,1]]
print(array3)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [32]:
import numpy
b=numpy.arange(1,7).reshape(2,-1)
b[[1, 0, 1, 0]][:,[0,1,2,0]]

array([[4, 5, 6, 4],
       [1, 2, 3, 1],
       [4, 5, 6, 4],
       [1, 2, 3, 1]])

In [41]:
import numpy
b=numpy.arange(1,10).reshape(3,-1)
print(b)
b[1:,:]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[4, 5, 6],
       [7, 8, 9]])

In [70]:
import numpy as np
a= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# 원하는 결과 출력:
# # array([[ 2],
#         [ 6],
#         [10]]) 

b=a[:,1]  #이렇게 하면 slicing element이므로 차원이 낮아져서 1차원이 반환됨
print(b, b.ndim)
print('----------------------------')

b=a[:,1:] #이렇게 하면 slicing이니까 차원이 유지되지만 원하는 결과 출력 안됨
print(b)
print('----------------------------')

b=a[:,1:2]
print(b)


[ 2  6 10] 1
----------------------------
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
----------------------------
[[ 2]
 [ 6]
 [10]]


In [63]:
myData=[2,4,6,8]
result = list(map(lambda x: x**2,myData))
print(result)

[4, 16, 36, 64]


### 자습 시간

In [54]:
import numpy as np
import pandas as pd

In [25]:
np.random.seed(10)
arr3=np.random.randint(1,30,16)
arr3

array([10,  5, 16,  1, 18, 28, 29, 26, 17, 18, 27,  9, 10,  1, 11,  9])

In [26]:
arr3_2= arr3.reshape(-1,4)
arr3_2

array([[10,  5, 16,  1],
       [18, 28, 29, 26],
       [17, 18, 27,  9],
       [10,  1, 11,  9]])

In [28]:
#bool_res=arr3_2>10
arr3_2[arr3_2>10]
#arr3_2

array([16, 18, 28, 29, 26, 17, 18, 27, 11])

In [18]:
#arr3_2[arr3_2>10]=0
#arr3_2

array([[10,  5,  0,  1],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  9],
       [10,  1,  0,  9]])

In [30]:
list('abcdef')

['a', 'b', 'c', 'd', 'e', 'f']

In [48]:
arr1=np.arange(1,15,1).reshape(7,-1)
arr1
arr1.astype(float)

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.],
       [11., 12.],
       [13., 14.]])

In [61]:
x=np.array([[1,2],[3,4]])
x=x.astype(float)
x.dtype

dtype('float64')

In [63]:
np.random.seed(10)
arr3=np.random.randint(1,30,16).reshape(-1,4)
arr3

array([[10,  5, 16,  1],
       [18, 28, 29, 26],
       [17, 18, 27,  9],
       [10,  1, 11,  9]])

In [5]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
arr[2,1:3]

array([7, 8])

In [74]:
arr.reshape(1,9)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [1]:
import numpy as np
import pandas as pd

a = np.arange(1,10,1).reshape(3,3)
df = pd.DataFrame(a, columns=['X1','X2','X3'], index=['A','B','C'])
df

X1  X2  X3
A   1   2   3
B   4   5   6
C   7   8   9

In [3]:
df=pd.read_csv('./HW/data.csv')

In [5]:
df

0        1          2          3       4      5         6       7  \
0     3030.93  2564.00  2187.7333  1411.1265  1.3602  100.0   97.6133  0.1242   
1     3095.78  2465.14  2230.4222  1463.6606  0.8294  100.0  102.3433  0.1247   
2     2932.61  2559.94  2186.4111  1698.0172  1.5102  100.0   95.4878  0.1241   
3     2988.72  2479.90  2199.0333   909.7926  1.3204  100.0  104.2367  0.1217   
4     3032.24  2502.87  2233.3667  1326.5200  1.5334  100.0  100.3967  0.1235   
...       ...      ...        ...        ...     ...    ...       ...     ...   
1562  2899.41  2464.36  2179.7333  3085.3781  1.4843  100.0   82.2467  0.1248   
1563  3052.31  2522.55  2198.5667  1124.6595  0.8763  100.0   98.4689  0.1205   
1564  2978.81  2379.78  2206.3000  1110.4967  0.8236  100.0   99.4122  0.1208   
1565  2894.92  2532.01  2177.0333  1183.7287  1.5726  100.0   98.7978  0.1213   
1566  2944.92  2450.76  2195.4444  2914.1792  1.5978  100.0   85.1011  0.1235   

           8       9  ...       581     582     583     584      585     586  \
0     1.5005  0.0162  ...    0.0000  0.5005  0.0118  0.0035   2.3630  0.0000   
1     1.4966 -0.0005  ...  208.2045  0.5019  0.0223  0.0055   4.4447  0.0096   
2     1.4436  0.0041  ...   82.8602  0.4958  0.0157  0.0039   3.1745  0.0584   
3     1.4882 -0.0124  ...   73.8432  0.4990  0.0103  0.0025   2.0544  0.0202   
4     1.5031 -0.0031  ...    0.0000  0.4800  0.4766  0.1045  99.3032  0.0202   
...      ...     ...  ...       ...     ...     ...     ...      ...     ...   
1562  1.3424 -0.0045  ...  203.1720  0.4988  0.0143  0.0039   2.8669  0.0068   
1563  1.4333 -0.0061  ...    0.0000  0.4975  0.0131  0.0036   2.6238  0.0068   
1564  0.0000  0.0000  ...   43.5231  0.4987  0.0153  0.0041   3.0590  0.0197   
1565  1.4622 -0.0072  ...   93.4941  0.5004  0.0178  0.0038   3.5662  0.0262   
1566  0.0000  0.0000  ...  137.7844  0.4987  0.0181  0.0040   3.6275  0.0117   

         587     588       589  Pass/Fail  
0     0.0000  0.0000    0.0000          0  
1     0.0201  0.0060  208.2045          0  
2     0.0484  0.0148   82.8602          1  
3     0.0149  0.0044   73.8432          0  
4     0.0149  0.0044   73.8432          0  
...      ...     ...       ...        ...  
1562  0.0138  0.0047  203.1720          0  
1563  0.0138  0.0047  203.1720          0  
1564  0.0086  0.0025   43.5231          0  
1565  0.0245  0.0075   93.4941          0  
1566  0.0162  0.0045  137.7844          0  

[1567 rows x 479 columns]

In [4]:
df.corr()

0         1         2         3         4         5  \
0          1.000000 -0.047782  0.007590  0.009448 -0.000915  0.008706   
1         -0.047782  1.000000 -0.030448  0.006021  0.002192 -0.030127   
2          0.007590 -0.030448  1.000000  0.323782  0.020438  0.990089   
3          0.009448  0.006021  0.323782  1.000000 -0.054015  0.286397   
4         -0.000915  0.002192  0.020438 -0.054015  1.000000  0.007041   
...             ...       ...       ...       ...       ...       ...   
586        0.044745 -0.009219  0.015733  0.038755 -0.043693  0.019435   
587        0.005233  0.039479 -0.007090 -0.038371 -0.030930 -0.003077   
588        0.003918  0.040500 -0.009122 -0.033648 -0.026046 -0.004919   
589        0.021489  0.044464 -0.030434 -0.084449  0.050741 -0.026117   
Pass/Fail  0.006149 -0.019672  0.024929 -0.016341 -0.013577  0.025315   

                  6         7         8         9  ...       581       582  \
0          0.006129  0.010738 -0.050979  0.009959  ... -0.033622  0.010503   
1         -0.031616 -0.025086  0.027609  0.003704  ...  0.043107 -0.017392   
2          0.818770  0.747230  0.002600 -0.045731  ...  0.038416 -0.010627   
3         -0.119180  0.279646 -0.108217  0.051567  ...  0.000922  0.009788   
4         -0.034736 -0.475861 -0.020082  0.053859  ...  0.107783  0.012778   
...             ...       ...       ...       ...  ...       ...       ...   
586       -0.005877  0.051943  0.017642  0.032423  ... -0.206109 -0.008240   
587        0.016362 -0.006335  0.027655  0.057856  ...  0.227096  0.018981   
588        0.013832 -0.014288  0.033729  0.059321  ...  0.216292  0.019083   
589        0.002246 -0.067263 -0.016895  0.004106  ...  0.431632  0.028502   
Pass/Fail  0.030075  0.023590  0.028376 -0.031209  ...  0.003478  0.018736   

                583       584       585       586       587       588  \
0          0.019840  0.017889  0.019522  0.044745  0.005233  0.003918   
1          0.003809  0.004409  0.003821 -0.009219  0.039479  0.040500   
2         -0.004771 -0.003030 -0.004263  0.015733 -0.007090 -0.009122   
3          0.022593  0.022361  0.023288  0.038755 -0.038371 -0.033648   
4         -0.001323 -0.001605 -0.001636 -0.043693 -0.030930 -0.026046   
...             ...       ...       ...       ...       ...       ...   
586        0.002391  0.001602  0.002872  1.000000  0.169634  0.165942   
587       -0.001809 -0.001696 -0.002122  0.169634  1.000000  0.974332   
588       -0.001445 -0.001182 -0.001746  0.165942  0.974332  1.000000   
589       -0.002453 -0.002750 -0.003266 -0.484741  0.391503  0.389898   
Pass/Fail  0.006131  0.005593  0.005179  0.004448  0.035670  0.031447   

                589  Pass/Fail  
0          0.021489   0.006149  
1          0.044464  -0.019672  
2         -0.030434   0.024929  
3         -0.084449  -0.016341  
4          0.050741  -0.013577  
...             ...        ...  
586       -0.484741   0.004448  
587        0.391503   0.035670  
588        0.389898   0.031447  
589        1.000000  -0.002472  
Pass/Fail -0.002472   1.000000  

[479 rows x 479 columns]