In [1]:
test = '13579'
test[::-1]


'97531'

In [8]:
a = [1, 3, 5, 7]
a.insert(len(a), 10)
a


[1, 3, 5, 7, 10]

In [1]:
grade = {'S': 10.0, 'A+': 9.5, 'A': 9.0,
         'B+': 8.5, 'B': 8.0, 'C': 7.5, 'D': 6.5}

grade['A']


9.0

In [1]:
A = 1
print(A)
sum()


1


TypeError: sum() takes at least 1 positional argument (0 given)

In [1]:
tot =0
for i in range(1,10,2):
    if i%3==0:
        break
    tot=tot+i
print(tot)

1


In [15]:
'B' and 0

0

In [6]:
'A' or 'B'

'A'

In [ ]:
int(h))

In [11]:
import numpy as np
from numpy import arange

b=arange(1,7).reshape(2,-1)
b[:1]

array([[1, 2, 3]])

In [14]:
x = np.array([0,1,2,3,4,5,6,7,8])

In [13]:
fidx = [3, 7, 1]
x[fidx]

array([3, 7, 1])

In [15]:
fidx =[[3, 7],
       [4, 2]]
fidx = np.array(fidx)
x[fidx]

array([[3, 7],
       [4, 2]])

In [16]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)

In [23]:
array=array2d[0,1]
print(array)
array3 = array2d[[0,1]]
print(array3)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [32]:
import numpy
b=numpy.arange(1,7).reshape(2,-1)
b[[1, 0, 1, 0]][:,[0,1,2,0]]

array([[4, 5, 6, 4],
       [1, 2, 3, 1],
       [4, 5, 6, 4],
       [1, 2, 3, 1]])

In [41]:
import numpy
b=numpy.arange(1,10).reshape(3,-1)
print(b)
b[1:,:]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[4, 5, 6],
       [7, 8, 9]])

In [70]:
import numpy as np
a= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# 원하는 결과 출력:
# # array([[ 2],
#         [ 6],
#         [10]]) 

b=a[:,1]  #이렇게 하면 slicing element이므로 차원이 낮아져서 1차원이 반환됨
print(b, b.ndim)
print('----------------------------')

b=a[:,1:] #이렇게 하면 slicing이니까 차원이 유지되지만 원하는 결과 출력 안됨
print(b)
print('----------------------------')

b=a[:,1:2]
print(b)


[ 2  6 10] 1
----------------------------
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
----------------------------
[[ 2]
 [ 6]
 [10]]


In [63]:
myData=[2,4,6,8]
result = list(map(lambda x: x**2,myData))
print(result)

[4, 16, 36, 64]


### 자습 시간

In [54]:
import numpy as np
import pandas as pd

In [25]:
np.random.seed(10)
arr3=np.random.randint(1,30,16)
arr3

array([10,  5, 16,  1, 18, 28, 29, 26, 17, 18, 27,  9, 10,  1, 11,  9])

In [26]:
arr3_2= arr3.reshape(-1,4)
arr3_2

array([[10,  5, 16,  1],
       [18, 28, 29, 26],
       [17, 18, 27,  9],
       [10,  1, 11,  9]])

In [28]:
#bool_res=arr3_2>10
arr3_2[arr3_2>10]
#arr3_2

array([16, 18, 28, 29, 26, 17, 18, 27, 11])

In [18]:
#arr3_2[arr3_2>10]=0
#arr3_2

array([[10,  5,  0,  1],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  9],
       [10,  1,  0,  9]])

In [30]:
list('abcdef')

['a', 'b', 'c', 'd', 'e', 'f']

In [48]:
arr1=np.arange(1,15,1).reshape(7,-1)
arr1
arr1.astype(float)

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.],
       [11., 12.],
       [13., 14.]])

In [61]:
x=np.array([[1,2],[3,4]])
x=x.astype(float)
x.dtype

dtype('float64')

In [63]:
np.random.seed(10)
arr3=np.random.randint(1,30,16).reshape(-1,4)
arr3

array([[10,  5, 16,  1],
       [18, 28, 29, 26],
       [17, 18, 27,  9],
       [10,  1, 11,  9]])

In [5]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
arr[2,1:3]

array([7, 8])

In [74]:
arr.reshape(1,9)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
import numpy as np
import pandas as pd

a = np.arange(1,10,1).reshape(3,3)
df = pd.DataFrame(a, columns=['X1','X2','X3'], index=['A','B','C'])
df

X1  X2  X3
A   1   2   3
B   4   5   6
C   7   8   9