In [2]:
import numpy as np
import pandas as pd

In [2]:
aa=[1,2,3]
aa[-2]=7
aa[1:2]=['a','b','c']
print(aa)

[1, 'a', 'b', 'c', 3]


In [6]:
def calc(type,*args):
    if(type=='add'):
        print(args[0]+args[2])
calc("add",3,4,6)

9


In [9]:
tot =0
for i in range(1,10,2):
    if i%3==0:
        continue
    tot +=i
print(tot)

13


In [14]:
arr = np.array([[103,815,571,934,599],
              [945, 71,669,639,116],
              [426,985,814,506,792],
              [295, 914,397,654,32],
              [859, 321,850,340,325]])
np.where(arr<300,-1,0)

array([[-1,  0,  0,  0,  0],
       [ 0, -1,  0,  0, -1],
       [ 0,  0,  0,  0,  0],
       [-1,  0,  0,  0, -1],
       [ 0,  0,  0,  0,  0]])

In [4]:
df = pd.read_csv('../강의 노트/1주차/tips.csv')
df=df[['tip', 'smoker']]
df

tip smoker
0    1.01     No
1    1.66     No
2    3.50     No
3    3.31     No
4    3.61     No
..    ...    ...
239  5.92     No
240  2.00    Yes
241  2.00    Yes
242  1.75     No
243  3.00     No

[244 rows x 2 columns]

In [10]:
df.loc[df['tip']>=2,'smoker'].value_counts()

No     121
Yes     78
Name: smoker, dtype: int64

In [42]:
df[df['tip']>2]
df['smoker'].value_counts()

No     151
Yes     93
Name: smoker, dtype: int64

In [43]:
a=(1,2,3,4)
a[2]=9

TypeError: 'tuple' object does not support item assignment

In [50]:
df=pd.read_excel('midterm8.xlsx')
df

a     b     c   d
0  20   NaN   1.0  10
1  11  12.0  19.0  37
2  10   8.0   NaN  25

In [52]:
df.sum(axis=1)

0    31.0
1    79.0
2    43.0
dtype: float64

In [56]:
df = pd.DataFrame([[7,6,9],[3,8,1],[5,4,2]], columns=list('CBA'))
df.loc[[1,0,2],['A','B','C']]

A  B  C
1  1  8  3
0  9  6  7
2  2  4  5

In [65]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[:, [0,2]])

[[1 3]
 [4 6]]


In [67]:
regions = [("NW", 55.3),("MW", 66.9),("South", 114.6),("West", 71.9)]
print(f'2010년 {regions[3][0]}의 인구는 {regions[3][1]}입니다')

2010년 West의 인구는 71.9입니다


In [68]:
arr1=np.arange(1,12,2).reshape(2,3)
print(arr1.sum(axis=0))

[ 8 12 16]


In [69]:
df=pd.read_excel('midterm15.xlsx')
df

A   B   C
0  13  20   7
1  16  22   8
2  22  19  24
3   1   5  15
4   4  24  18
5   4   7   6
6   8  13  14
7  10   2   9

In [75]:
result = df.max().min()

print(result)

22


In [78]:
df=pd.read_excel('midterm16.xlsx')
df

product  price  count
0       A    100     12
1       B     70      5
2       C     75      8
3       D     90      3

In [80]:
df['total']=df['price']*df['count']
df

product  price  count  total
0       A    100     12   1200
1       B     70      5    350
2       C     75      8    600
3       D     90      3    270

In [85]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b[[0,1,2],[0,1,2]])
b[[0,1,2],[0,1,2]]

[1 5 9]


array([1, 5, 9])

In [97]:
df=pd.read_excel('midterm18.xlsx')
df.index=['A','B','C']
df

X1  X2  X3
A   1   2   3
B   4   5   6
C   7   8   9

In [98]:
df[df['X1']%2==0]

X1  X2  X3
B   4   5   6

In [101]:
df=pd.read_excel('midterm20.xlsx')
df.index=['A','B','C','D']
df

X1   X2    X3
A NaN  1.0   2.0
B NaN  4.0   NaN
C NaN  7.0   8.0
D NaN  NaN  11.0

In [139]:
display(df.sum(axis=0,skipna=True)) #axis=0이니까 열을 기준으로 sum 실행

display(df.dropna(axis=0, thresh=2)) #axis=0인데 왜 열을 기준으로 삭제??

display(df.dropna(axis=1, thresh=2)) #axis=1인데 왜 행을 기준으로 삭제??


X1     0.0
X2    12.0
X3    21.0
dtype: float64

X1   X2   X3
A NaN  1.0  2.0
C NaN  7.0  8.0

X2    X3
A  1.0   2.0
B  4.0   NaN
C  7.0   8.0
D  NaN  11.0